// <auto-generated />
using System;
using LocalVenico.Web.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LocalVenico.Web.Data.Migraciones
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260619023239_AgregarCamposImpresora")]
    partial class AgregarCamposImpresora
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LocalVenico.Web.Data.Entidades.Categoria", b =>
                {
                    b.Property<int>("CategoriaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("categoria_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoriaId"));

                    b.Property<bool>("Activa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("activa");

                    b.Property<DateTime>("CreadoEn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("creado_en")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("descripcion");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("nombre");

                    b.HasKey("CategoriaId");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("categorias", (string)null);

                    b.HasData(
                        new
                        {
                            CategoriaId = 1,
                            Activa = true,
                            CreadoEn = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Abarrotes"
                        },
                        new
                        {
                            CategoriaId = 2,
                            Activa = true,
                            CreadoEn = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Bebestibles"
                        },
                        new
                        {
                            CategoriaId = 3,
                            Activa = true,
                            CreadoEn = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Lácteos"
                        },
                        new
                        {
                            CategoriaId = 4,
                            Activa = true,
                            CreadoEn = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Panadería y Pastelería"
                        },
                        new
                        {
                            CategoriaId = 5,
                            Activa = true,
                            CreadoEn = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Frutas y Verduras"
                        },
                        new
                        {
                            CategoriaId = 6,
                            Activa = true,
                            CreadoEn = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Carnes y Embutidos"
                        },
                        new
                        {
                            CategoriaId = 7,
                            Activa = true,
                            CreadoEn = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Limpieza y Hogar"
                        },
                        new
                        {
                            CategoriaId = 8,
                            Activa = true,
                            CreadoEn = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Higiene Personal"
                        },
                        new
                        {
                            CategoriaId = 9,
                            Activa = true,
                            CreadoEn = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Snacks y Confites"
                        },
                        new
                        {
                            CategoriaId = 10,
                            Activa = true,
                            CreadoEn = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Congelados"
                        },
                        new
                        {
                            CategoriaId = 11,
                            Activa = true,
                            CreadoEn = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Otros"
                        });
                });

            modelBuilder.Entity("LocalVenico.Web.Data.Entidades.ConfigImpresora", b =>
                {
                    b.Property<int>("ConfigId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("config_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ConfigId"));

                    b.Property<bool>("Activa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("activa");

                    b.Property<DateTime>("ActualizadoEn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("actualizado_en")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int>("AnchoPapelMm")
                        .HasColumnType("int");

                    b.Property<int>("CaracteresPorLinea")
                        .HasColumnType("int");

                    b.Property<int>("CopiasImpresion")
                        .HasColumnType("int");

                    b.Property<bool>("CorteAutomatico")
                        .HasColumnType("bit");

                    b.Property<int>("LineasEncabezado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(3)
                        .HasColumnName("lineas_encabezado");

                    b.Property<int>("LineasPie")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(3)
                        .HasColumnName("lineas_pie");

                    b.Property<string>("LogoTexto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MensajePieBoleta")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("MostrarLogo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("mostrar_logo");

                    b.Property<string>("NombreImpresora")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("nombre_impresora");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("TERMICA_80MM")
                        .HasColumnName("tipo");

                    b.HasKey("ConfigId");

                    b.ToTable("config_impresora", (string)null);
                });

            modelBuilder.Entity("LocalVenico.Web.Data.Entidades.DetalleOrdenCompra", b =>
                {
                    b.Property<int>("DetalleOrdenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("detalle_orden_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DetalleOrdenId"));

                    b.Property<decimal>("CantidadPedida")
                        .HasPrecision(12, 3)
                        .HasColumnType("decimal(12,3)")
                        .HasColumnName("cantidad_pedida");

                    b.Property<decimal>("CantidadRecibida")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(12, 3)
                        .HasColumnType("decimal(12,3)")
                        .HasDefaultValue(0m)
                        .HasColumnName("cantidad_recibida");

                    b.Property<int>("OrdenId")
                        .HasColumnType("int")
                        .HasColumnName("orden_id");

                    b.Property<decimal>("PrecioUnitarioCompra")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("precio_unitario_compra");

                    b.Property<int>("ProductoId")
                        .HasColumnType("int")
                        .HasColumnName("producto_id");

                    b.Property<decimal>("Subtotal")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("subtotal");

                    b.HasKey("DetalleOrdenId");

                    b.HasIndex("OrdenId");

                    b.HasIndex("ProductoId");

                    b.ToTable("detalle_orden_compra", (string)null);
                });

            modelBuilder.Entity("LocalVenico.Web.Data.Entidades.DetalleVenta", b =>
                {
                    b.Property<int>("DetalleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("detalle_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DetalleId"));

                    b.Property<decimal>("Cantidad")
                        .HasPrecision(12, 3)
                        .HasColumnType("decimal(12,3)")
                        .HasColumnName("cantidad");

                    b.Property<string>("CodigoBarras")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("codigo_barras");

                    b.Property<decimal>("DescuentoItem")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("descuento_item");

                    b.Property<string>("NombreProducto")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("nombre_producto");

                    b.Property<decimal>("PrecioUnitario")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("precio_unitario");

                    b.Property<int>("ProductoId")
                        .HasColumnType("int")
                        .HasColumnName("producto_id");

                    b.Property<decimal>("Subtotal")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("subtotal");

                    b.Property<int>("VentaId")
                        .HasColumnType("int")
                        .HasColumnName("venta_id");

                    b.HasKey("DetalleId");

                    b.HasIndex("ProductoId");

                    b.HasIndex("VentaId");

                    b.ToTable("detalle_venta", (string)null);
                });

            modelBuilder.Entity("LocalVenico.Web.Data.Entidades.Empresa", b =>
                {
                    b.Property<int>("EmpresaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("empresa_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmpresaId"));

                    b.Property<DateTime>("ActualizadoEn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("actualizado_en")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Comuna")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("comuna");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("direccion");

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("email");

                    b.Property<string>("Giro")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasDefaultValue("Almacén de Abarrotes")
                        .HasColumnName("giro");

                    b.Property<string>("LogoRuta")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("logo_ruta");

                    b.Property<string>("Moneda")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)")
                        .HasDefaultValue("CLP")
                        .HasColumnName("moneda");

                    b.Property<int>("NumeroBoleta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1)
                        .HasColumnName("numero_boleta_inicio");

                    b.Property<decimal>("PorcentajeIva")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)")
                        .HasDefaultValue(19m)
                        .HasColumnName("porcentaje_iva");

                    b.Property<bool>("PreciosConIva")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("precios_con_iva");

                    b.Property<string>("RazonSocial")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("razon_social");

                    b.Property<string>("Region")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasDefaultValue("Metropolitana")
                        .HasColumnName("region");

                    b.Property<string>("Rut")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)")
                        .HasColumnName("rut");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("telefono");

                    b.HasKey("EmpresaId");

                    b.ToTable("empresa", (string)null);
                });

            modelBuilder.Entity("LocalVenico.Web.Data.Entidades.MedioPago", b =>
                {
                    b.Property<int>("MedioPagoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("medio_pago_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MedioPagoId"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("activo");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("nombre");

                    b.Property<bool>("RequiereVuelto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("requiere_vuelto");

                    b.HasKey("MedioPagoId");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("medios_pago", (string)null);

                    b.HasData(
                        new
                        {
                            MedioPagoId = 1,
                            Activo = true,
                            Nombre = "Efectivo",
                            RequiereVuelto = true
                        },
                        new
                        {
                            MedioPagoId = 2,
                            Activo = true,
                            Nombre = "Débito",
                            RequiereVuelto = false
                        },
                        new
                        {
                            MedioPagoId = 3,
                            Activo = true,
                            Nombre = "Crédito",
                            RequiereVuelto = false
                        },
                        new
                        {
                            MedioPagoId = 4,
                            Activo = true,
                            Nombre = "Transferencia",
                            RequiereVuelto = false
                        });
                });

            modelBuilder.Entity("LocalVenico.Web.Data.Entidades.OrdenCompra", b =>
                {
                    b.Property<int>("OrdenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("orden_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrdenId"));

                    b.Property<int>("CreadoPor")
                        .HasColumnType("int")
                        .HasColumnName("creado_por");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("BORRADOR")
                        .HasColumnName("estado");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha_creacion")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateTime?>("FechaRecepcion")
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha_recepcion");

                    b.Property<string>("Notas")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("notas");

                    b.Property<int>("NumeroOrden")
                        .HasColumnType("int")
                        .HasColumnName("numero_orden");

                    b.Property<int>("ProveedorId")
                        .HasColumnType("int")
                        .HasColumnName("proveedor_id");

                    b.Property<int?>("RecibidoPor")
                        .HasColumnType("int")
                        .HasColumnName("recibido_por");

                    b.Property<decimal>("TotalEstimado")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("total_estimado");

                    b.HasKey("OrdenId");

                    b.HasIndex("CreadoPor");

                    b.HasIndex("ProveedorId");

                    b.HasIndex("RecibidoPor");

                    b.ToTable("ordenes_compra", (string)null);
                });

            modelBuilder.Entity("LocalVenico.Web.Data.Entidades.Producto", b =>
                {
                    b.Property<int>("ProductoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("producto_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductoId"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("activo");

                    b.Property<DateTime>("ActualizadoEn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("actualizado_en")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int>("CategoriaId")
                        .HasColumnType("int")
                        .HasColumnName("categoria_id");

                    b.Property<string>("CodigoBarras")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("codigo_barras");

                    b.Property<string>("CodigoInterno")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("codigo_interno");

                    b.Property<DateTime>("CreadoEn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("creado_en")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("descripcion");

                    b.Property<string>("ImagenUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("imagen_url");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("nombre");

                    b.Property<decimal>("PrecioCompra")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("precio_compra");

                    b.Property<decimal>("PrecioVenta")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("precio_venta");

                    b.Property<decimal>("StockActual")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(12, 3)
                        .HasColumnType("decimal(12,3)")
                        .HasDefaultValue(0m)
                        .HasColumnName("stock_actual");

                    b.Property<decimal>("StockMinimo")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(12, 3)
                        .HasColumnType("decimal(12,3)")
                        .HasDefaultValue(0m)
                        .HasColumnName("stock_minimo");

                    b.Property<bool>("TieneCodigoPropio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("tiene_codigo_propio");

                    b.Property<string>("UnidadMedida")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("UN")
                        .HasColumnName("unidad_medida");

                    b.HasKey("ProductoId");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("CodigoBarras")
                        .IsUnique()
                        .HasFilter("[codigo_barras] IS NOT NULL");

                    b.HasIndex("CodigoInterno")
                        .IsUnique();

                    b.HasIndex("Nombre");

                    b.ToTable("productos", (string)null);
                });

            modelBuilder.Entity("LocalVenico.Web.Data.Entidades.Proveedor", b =>
                {
                    b.Property<int>("ProveedorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("proveedor_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProveedorId"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("activo");

                    b.Property<DateTime>("CreadoEn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("creado_en")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Direccion")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("direccion");

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("email");

                    b.Property<string>("NombreContacto")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("nombre_contacto");

                    b.Property<string>("Notas")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("notas");

                    b.Property<string>("RazonSocial")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("razon_social");

                    b.Property<string>("Rut")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)")
                        .HasColumnName("rut");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("telefono");

                    b.HasKey("ProveedorId");

                    b.ToTable("proveedores", (string)null);
                });

            modelBuilder.Entity("LocalVenico.Web.Data.Entidades.Rol", b =>
                {
                    b.Property<int>("RolId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("rol_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RolId"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("activo");

                    b.Property<DateTime>("CreadoEn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("creado_en")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("descripcion");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("nombre");

                    b.HasKey("RolId");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("roles", (string)null);

                    b.HasData(
                        new
                        {
                            RolId = 1,
                            Activo = true,
                            CreadoEn = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descripcion = "Acceso total al sistema",
                            Nombre = "admin"
                        },
                        new
                        {
                            RolId = 2,
                            Activo = true,
                            CreadoEn = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descripcion = "Acceso al punto de venta e inventario básico",
                            Nombre = "cajero"
                        },
                        new
                        {
                            RolId = 3,
                            Activo = true,
                            CreadoEn = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descripcion = "Acceso a inventario, stock y recepciones",
                            Nombre = "bodeguero"
                        });
                });

            modelBuilder.Entity("LocalVenico.Web.Data.Entidades.Sesion", b =>
                {
                    b.Property<Guid>("SesionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("sesion_id")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<bool>("Activa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("activa");

                    b.Property<DateTime>("CreadoEn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("creado_en")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateTime>("ExpiraEn")
                        .HasColumnType("datetime2")
                        .HasColumnName("expira_en");

                    b.Property<string>("IpOrigen")
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)")
                        .HasColumnName("ip_origen");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("token_hash");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int")
                        .HasColumnName("usuario_id");

                    b.HasKey("SesionId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("sesiones", (string)null);
                });

            modelBuilder.Entity("LocalVenico.Web.Data.Entidades.StockMovimiento", b =>
                {
                    b.Property<int>("MovimientoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("movimiento_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MovimientoId"));

                    b.Property<decimal>("Cantidad")
                        .HasPrecision(12, 3)
                        .HasColumnType("decimal(12,3)")
                        .HasColumnName("cantidad");

                    b.Property<DateTime>("CreadoEn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("creado_en")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Motivo")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("motivo");

                    b.Property<int?>("OrdenCompraId")
                        .HasColumnType("int")
                        .HasColumnName("orden_compra_id");

                    b.Property<int>("ProductoId")
                        .HasColumnType("int")
                        .HasColumnName("producto_id");

                    b.Property<decimal>("StockAntes")
                        .HasPrecision(12, 3)
                        .HasColumnType("decimal(12,3)")
                        .HasColumnName("stock_antes");

                    b.Property<decimal>("StockDespues")
                        .HasPrecision(12, 3)
                        .HasColumnType("decimal(12,3)")
                        .HasColumnName("stock_despues");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("tipo");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int")
                        .HasColumnName("usuario_id");

                    b.Property<int?>("VentaId")
                        .HasColumnType("int")
                        .HasColumnName("venta_id");

                    b.HasKey("MovimientoId");

                    b.HasIndex("OrdenCompraId");

                    b.HasIndex("ProductoId");

                    b.HasIndex("UsuarioId");

                    b.HasIndex("VentaId");

                    b.ToTable("stock_movimientos", (string)null);
                });

            modelBuilder.Entity("LocalVenico.Web.Data.Entidades.Usuario", b =>
                {
                    b.Property<int>("UsuarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("usuario_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UsuarioId"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("activo");

                    b.Property<DateTime>("CreadoEn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("creado_en")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("nombre_completo");

                    b.Property<string>("NombreUsuario")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("nombre_usuario");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("password_hash");

                    b.Property<int>("RolId")
                        .HasColumnType("int")
                        .HasColumnName("rol_id");

                    b.Property<DateTime?>("UltimoAcceso")
                        .HasColumnType("datetime2")
                        .HasColumnName("ultimo_acceso");

                    b.HasKey("UsuarioId");

                    b.HasIndex("NombreUsuario")
                        .IsUnique();

                    b.HasIndex("RolId");

                    b.ToTable("usuarios", (string)null);

                    b.HasData(
                        new
                        {
                            UsuarioId = 1,
                            Activo = true,
                            CreadoEn = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NombreCompleto = "Administrador",
                            NombreUsuario = "admin",
                            PasswordHash = "$2a$12$LQv3c1yqBWVHxkd0LHAkCOYz6TtxMQJqhN8/LewdBPj7oFJDKHbPm",
                            RolId = 1
                        });
                });

            modelBuilder.Entity("LocalVenico.Web.Data.Entidades.Venta", b =>
                {
                    b.Property<int>("VentaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("venta_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VentaId"));

                    b.Property<int?>("AnuladaPor")
                        .HasColumnType("int")
                        .HasColumnName("anulada_por");

                    b.Property<decimal>("DescuentoTotal")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("descuento_total");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("COMPLETADA")
                        .HasColumnName("estado");

                    b.Property<DateTime?>("FechaAnulacion")
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha_anulacion");

                    b.Property<DateTime>("FechaVenta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha_venta")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int>("MedioPagoId")
                        .HasColumnType("int")
                        .HasColumnName("medio_pago_id");

                    b.Property<decimal>("MontoIva")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("monto_iva");

                    b.Property<decimal>("MontoPagado")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("monto_pagado");

                    b.Property<string>("MotivoAnulacion")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("motivo_anulacion");

                    b.Property<int>("NumeroBoleta")
                        .HasColumnType("int")
                        .HasColumnName("numero_boleta");

                    b.Property<decimal>("SubtotalNeto")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("subtotal_neto");

                    b.Property<decimal>("Total")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("total");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int")
                        .HasColumnName("usuario_id");

                    b.Property<decimal>("Vuelto")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("vuelto");

                    b.HasKey("VentaId");

                    b.HasIndex("AnuladaPor");

                    b.HasIndex("FechaVenta");

                    b.HasIndex("MedioPagoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("ventas", (string)null);
                });

            modelBuilder.Entity("LocalVenico.Web.Data.Entidades.DetalleOrdenCompra", b =>
                {
                    b.HasOne("LocalVenico.Web.Data.Entidades.OrdenCompra", "OrdenCompra")
                        .WithMany("Detalles")
                        .HasForeignKey("OrdenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LocalVenico.Web.Data.Entidades.Producto", "Producto")
                        .WithMany("DetallesOrden")
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OrdenCompra");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("LocalVenico.Web.Data.Entidades.DetalleVenta", b =>
                {
                    b.HasOne("LocalVenico.Web.Data.Entidades.Producto", "Producto")
                        .WithMany("DetallesVenta")
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LocalVenico.Web.Data.Entidades.Venta", "Venta")
                        .WithMany("Detalles")
                        .HasForeignKey("VentaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Producto");

                    b.Navigation("Venta");
                });

            modelBuilder.Entity("LocalVenico.Web.Data.Entidades.OrdenCompra", b =>
                {
                    b.HasOne("LocalVenico.Web.Data.Entidades.Usuario", "UsuarioCreador")
                        .WithMany("OrdenesCreadas")
                        .HasForeignKey("CreadoPor")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LocalVenico.Web.Data.Entidades.Proveedor", "Proveedor")
                        .WithMany("Ordenes")
                        .HasForeignKey("ProveedorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LocalVenico.Web.Data.Entidades.Usuario", "UsuarioReceptor")
                        .WithMany("OrdenesRecibidas")
                        .HasForeignKey("RecibidoPor");

                    b.Navigation("Proveedor");

                    b.Navigation("UsuarioCreador");

                    b.Navigation("UsuarioReceptor");
                });

            modelBuilder.Entity("LocalVenico.Web.Data.Entidades.Producto", b =>
                {
                    b.HasOne("LocalVenico.Web.Data.Entidades.Categoria", "Categoria")
                        .WithMany("Productos")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("LocalVenico.Web.Data.Entidades.Sesion", b =>
                {
                    b.HasOne("LocalVenico.Web.Data.Entidades.Usuario", "Usuario")
                        .WithMany("Sesiones")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("LocalVenico.Web.Data.Entidades.StockMovimiento", b =>
                {
                    b.HasOne("LocalVenico.Web.Data.Entidades.OrdenCompra", "OrdenCompra")
                        .WithMany("Movimientos")
                        .HasForeignKey("OrdenCompraId");

                    b.HasOne("LocalVenico.Web.Data.Entidades.Producto", "Producto")
                        .WithMany("Movimientos")
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LocalVenico.Web.Data.Entidades.Usuario", "Usuario")
                        .WithMany("Movimientos")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LocalVenico.Web.Data.Entidades.Venta", "Venta")
                        .WithMany("Movimientos")
                        .HasForeignKey("VentaId");

                    b.Navigation("OrdenCompra");

                    b.Navigation("Producto");

                    b.Navigation("Usuario");

                    b.Navigation("Venta");
                });

            modelBuilder.Entity("LocalVenico.Web.Data.Entidades.Usuario", b =>
                {
                    b.HasOne("LocalVenico.Web.Data.Entidades.Rol", "Rol")
                        .WithMany("Usuarios")
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("LocalVenico.Web.Data.Entidades.Venta", b =>
                {
                    b.HasOne("LocalVenico.Web.Data.Entidades.Usuario", "UsuarioAnulacion")
                        .WithMany()
                        .HasForeignKey("AnuladaPor");

                    b.HasOne("LocalVenico.Web.Data.Entidades.MedioPago", "MedioPago")
                        .WithMany("Ventas")
                        .HasForeignKey("MedioPagoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LocalVenico.Web.Data.Entidades.Usuario", "Usuario")
                        .WithMany("Ventas")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MedioPago");

                    b.Navigation("Usuario");

                    b.Navigation("UsuarioAnulacion");
                });

            modelBuilder.Entity("LocalVenico.Web.Data.Entidades.Categoria", b =>
                {
                    b.Navigation("Productos");
                });

            modelBuilder.Entity("LocalVenico.Web.Data.Entidades.MedioPago", b =>
                {
                    b.Navigation("Ventas");
                });

            modelBuilder.Entity("LocalVenico.Web.Data.Entidades.OrdenCompra", b =>
                {
                    b.Navigation("Detalles");

                    b.Navigation("Movimientos");
                });

            modelBuilder.Entity("LocalVenico.Web.Data.Entidades.Producto", b =>
                {
                    b.Navigation("DetallesOrden");

                    b.Navigation("DetallesVenta");

                    b.Navigation("Movimientos");
                });

            modelBuilder.Entity("LocalVenico.Web.Data.Entidades.Proveedor", b =>
                {
                    b.Navigation("Ordenes");
                });

            modelBuilder.Entity("LocalVenico.Web.Data.Entidades.Rol", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("LocalVenico.Web.Data.Entidades.Usuario", b =>
                {
                    b.Navigation("Movimientos");

                    b.Navigation("OrdenesCreadas");

                    b.Navigation("OrdenesRecibidas");

                    b.Navigation("Sesiones");

                    b.Navigation("Ventas");
                });

            modelBuilder.Entity("LocalVenico.Web.Data.Entidades.Venta", b =>
                {
                    b.Navigation("Detalles");

                    b.Navigation("Movimientos");
                });
#pragma warning restore 612, 618
        }
    }
}
